[tool.poetry]
name = "survey-studio"
version = "0.0.1"
description = "A multi-agent literature review assistant using AutoGen and Streamlit"
authors = ["Survey Studio Team <team@surveystudio.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/survey-studio/survey-studio"
repository = "https://github.com/survey-studio/survey-studio"
keywords = ["literature-review", "autogen", "streamlit", "arxiv", "research"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Text Processing :: General",
]
packages = [{include = "survey_studio", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11.9"
streamlit = "^1.38.0"
arxiv = "^2.1.0"
autogen-core = "^0.4.1"
autogen-agentchat = "^0.4.1"
autogen-ext = "^0.4.1"
openai = "^1.53.0"
tenacity = "^8.5.0"
tiktoken = "^0.11.0"

[tool.poetry.group.dev.dependencies]
ruff = "0.6.9"
mypy = "1.11.1"
pytest = "8.3.2"
pytest-asyncio = "0.23.8"
pytest-cov = "5.0.0"
coverage = "7.6.1"
pre-commit = "3.8.0"

[tool.poetry.scripts]
survey-studio = "survey_studio.app:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"
line-length = 88
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
    "N",  # pep8-naming
]
ignore = []
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**/*" = ["N806"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
show_column_numbers = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "arxiv.*",
    "autogen_core.*",
    "autogen_agentchat.*",
    "autogen_ext.*",
    "streamlit.*"
]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-ra",
    "--strict-markers",
    "--strict-config",
    "--cov=src/survey_studio",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
    "--cov-fail-under=95"
]
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
show_missing = true
fail_under = 95
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]