# Streamlit theme configuration
# Accessible, professional theme suitable for academic/research apps

[theme]
base = "light"
primaryColor = "#2563EB"            # Blue 600
backgroundColor = "#FFFFFF"          # White
secondaryBackgroundColor = "#F3F4F6" # Gray 100/200
textColor = "#111827"                # Gray 900
font = "sans serif"

# Notes:
# - The app supports users switching to dark mode via Streamlit's theme controls.
# - Colors were selected for WCAG AA contrast ratios and readability.

[global]
# Global configuration for Streamlit

[server]
# Server configuration
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[logger]
# Logging configuration
level = "info"
